# Generated by Django 4.2 on 2023-04-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.CharField(max_length=150, verbose_name='Завтрак')),
                ('lunch', models.CharField(max_length=150, verbose_name='Завтрак')),
                ('dinner', models.CharField(max_length=150, verbose_name='Завтрак')),
                ('other_food', models.CharField(max_length=150, verbose_name='Завтрак')),
            ],
        ),
    ]
