# Generated by Django 4.2.2 on 2023-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sugar', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Sugar',
                'verbose_name_plural': 'Sugars',
            },
        ),
        migrations.AlterModelOptions(
            name='foodperday',
            options={'verbose_name': 'Food in day', 'verbose_name_plural': 'Food in days'},
        ),
        migrations.AlterField(
            model_name='foodperday',
            name='breakfast',
            field=models.CharField(max_length=150, verbose_name='breakfast'),
        ),
        migrations.AlterField(
            model_name='foodperday',
            name='dinner',
            field=models.CharField(max_length=150, verbose_name='dinner'),
        ),
        migrations.AlterField(
            model_name='foodperday',
            name='lunch',
            field=models.CharField(max_length=150, verbose_name='lunch'),
        ),
        migrations.AlterField(
            model_name='foodperday',
            name='other_food',
            field=models.CharField(max_length=150, verbose_name='other food'),
        ),
    ]
